name: action-playground # A place to test / refine github actions

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: lts/gallium
          cache: yarn
      - name: Cache dependencies
        uses: actions/cache@v3.3.2
        with:
          path: '**/node_modules'
          key: check-gallery-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install
        run: yarn
      - name: Check gallery
        shell: bash
        run: |
          yarn update-gallery-config
          if [[ `git status --porcelain` ]]; then
            echo "Gallery config is up to date."
          else
            core.setFailed('The gallery is out of date, run `yarn update-gallery-config`')
          fi
