# Creates and pushes release tag, then creates release notes from the changelogs.
# Creates PR to merge changelog and version bump updates from release to main branch
name: Create change log

on:
  workflow_dispatch:
    inputs:
      tag:
        # Recently published version
        required: true
        description: 'release tag (ie. v2.46.0-rc.0)'
        type: string
        default: 'v2.46.0-rc.0'
      previous-tag:
        # Previous release tag to grab changelogs from
        # To pick the previous tag:
        # - If published tag is the first release candidate, choose the previous full release tag.
        # - If published tag is a subsequent release candidate, choose the previous release candidate.
        # - If published tag is a full release, choose the previous full release tag.
        required: true
        description: 'previous release tag (ie. v2.45.0)'
        type: string
        default: 'v2.45.0'
      create-pr:
        # set to true to create PR to merge changes from release to `main` branch
        required: true
        description: 'Create PR?'
        type: boolean
        default: true

jobs:
  changelog:
    name: Generate changelog between tags
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: '0'
      - name: Fetch all tags
        run: |
          git fetch --tags origin
          echo "✅ Tags fetched:"
          git tag -l | sort -V | tail -n 10
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install

      - name: Generate changelog
        run: |
          node ./scripts/get-changelog.js \
            -f ${{ github.event.inputs.previous-tag }} \
            -t ${{ github.event.inputs.tag }}
          echo "📄 changelog.txt contents:"
          cat changelog.txt

      - name: Upload changelog artifact
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: changelog.txt