name: Visual Regression Testing

on:
  pull_request:
    branches:
      - main
      - percySnapshot
      - percySnapshot_1
  issue_comment:
    types: [created]

jobs:
  vrt-runner:
    runs-on: ubuntu-latest
    env:
      PERCY_TOKEN: 'web_d04495b0b413d61c2ea6b9118d1748b43f4fdd58d17ebe453ef8e0016b5766e4'

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: debug
        run: "echo Comment body: ${{ github.event.comment.body }}"
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install browsers
        run: yarn playwright install --with-deps

      - name: Build project
        run: yarn build

      - name: Run Percy VRT
        working-directory: packages/core
        run: yarn percy storybook storybook-static
