name: Visual Regression Testing

on:
  issue_comment:
    types: [created]

jobs:
  vrt-runner:
    if: |
      github.event.issue.pull_request &&
      github.event.comment.body == '/run-vrt'
    runs-on: ubuntu-latest
    env:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_IBM_PRODUCTS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          cache: yarn

      - name: Install
        run: yarn

      - name: Install browsers
        run: yarn playwright install --with-deps

      - name: Build project
        run: yarn build

      - name: Run VRT
        working-directory: packages/core
        run: yarn percy storybook storybook-static